# vim: set ts=2 sw=2 sts=2 et:
#
# Metadata
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

version: 5.5.0.0
type: common
authorName: Qualiteam
moduleName: 'SkinAct. Mobile App only banners'
description: 'Mobile App only banners, SS-22809'
minorRequiredCoreVersion: 0
dependsOn:
  - QSL-Banner
  - Qualiteam-SkinActGraphQLApi
incompatibleWith: {  }
showSettingsForm: false
canDisable: true
