version: 5.5.0.0
type: common
authorName: Qualiteam
moduleName: '[SkinAct] Today''s deal mobile app'
description: '[CANCELED since the feature is changed into Sale block products]. Added a block "Today''s deal" for mobile app as the specified category''s products list'
minorRequiredCoreVersion: 0
dependsOn: {  }
incompatibleWith: {  }
skins: {  }
showSettingsForm: true
canDisable: true
