# vim: set ts=2 sw=2 sts=2 et:
#
# Metadata
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

version: 5.5.0.0
type: skin
authorName: 'Qualiteam'
moduleName: 'SkinAct Skin'
description: 'Module provides unique design for www.spaandequipment.com'
minorRequiredCoreVersion: 0
dependsOn:
  - XC-CrispWhiteSkin
incompatibleWith: {  }
showSettingsForm: false
canDisable: true