#
# Module services
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

api_platform:
    resource_class_directories:
        - '%kernel.project_dir%/var/run/classes/XC/ProductVariants/Model'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    XC\ProductVariants\LifetimeHook\Hook:
        tags:
            - { name: xcart.lifetime-hook, moduleId: XC-ProductVariants, type: install, method: onInstall }
            - { name: xcart.lifetime-hook, moduleId: XC-ProductVariants, type: upgrade, method: onUpgradeTo5500, version: '5.5.0.0' }

    # /product/{product_id}/variants
    XC\ProductVariants\API\Endpoint\ProductVariant\Transformer\OutputTransformerInterface: '@XC\ProductVariants\API\Endpoint\ProductVariant\Transformer\OutputTransformer'
    XC\ProductVariants\API\Endpoint\ProductVariant\Transformer\OutputTransformer: ~
    XC\ProductVariants\API\Endpoint\ProductVariant\Transformer\InputTransformerInterface: '@XC\ProductVariants\API\Endpoint\ProductVariant\Transformer\InputTransformer'
    XC\ProductVariants\API\Endpoint\ProductVariant\Transformer\InputTransformer: ~

    XC\ProductVariants\API\Endpoint\ProductVariant\SubIriConverter\SubIriConverter:
        tags: [ !php/const XCart\Framework\ApiPlatform\Core\Bridge\Symfony\Routing\SubIriConverter\SubIriFromItemConverterInterface::SUB_IRI_FROM_ITEM_CONVERTER_TAG ]

    XC\ProductVariants\API\Endpoint\ProductVariant\DataProvider\CollectionDataProvider:
        arguments:
            $inner: '@api_platform.doctrine.orm.default.collection_data_provider'
            $repository: '@xcart.repository.product'

    XC\ProductVariants\API\Endpoint\ProductVariant\DataProvider\ItemDataProvider:
        arguments:
            $inner: '@api_platform.doctrine.orm.default.item_data_provider'
            $repository: '@xcart.repository.product'

    xcart.api.xc.product_variants.product_variant.controller:
        class: XC\ProductVariants\Controller\API\ProductVariant\Post
        arguments:
            $repository: '@xcart.repository.product'

    XC\ProductVariants\API\OpenApiTagsRepositoryDecorator:
        decorates: XLite\API\OpenApiTagsRepository

    xcart.api.xc.ProductVariants.product_ProductVariants_product.sub_extension:
        class: XC\ProductVariants\API\Endpoint\ProductVariant\SubExtension\SubExtension
        tags: [ !php/const XLite\API\Extension\CollectionSubExtension\CollectionSubExtensionInterface::COLLECTION_SUB_EXTENSION_TAG, !php/const XLite\API\Extension\ItemSubExtension\ItemSubExtensionInterface::ITEM_SUB_EXTENSION_TAG ]

    XC\ProductVariants\Controller\API\ProductVariant\Delete:
        tags: [ 'controller.service_arguments' ]

    XC\ProductVariants\Controller\API\ProductVariant\Put:
        tags: [ 'controller.service_arguments' ]
