version: 5.5.0.0
type: common
authorName: Qualiteam
moduleName: 'SkinAct. GraphQL API Provider'
description: 'SkinAct. Provides programmatic GraphQL access to the storefront'
minorRequiredCoreVersion: 0
dependsOn:
  - Qualiteam-SkinActMain

incompatibleWith: { }
skins: { }
showSettingsForm: false
canDisable: true
