# vim: set ts=2 sw=2 sts=2 et:
#
# Metadata
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

version: 5.5.0.1
type: payment
authorName: 'X-Cart team'
moduleName: 'Moneris (eSELECTplus- Hosted Pay Page)'
description: 'Accept credit and debit cards via an online transaction processing engine. USA and Canada'
minorRequiredCoreVersion: 0
dependsOn: {  }
incompatibleWith: {  }
showSettingsForm: false
canDisable: true
