#
# Module services
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

services:
  _defaults:
    autowire: true

  Qualiteam\SkinActXPaymentsConnector\LifetimeHook\Hook:
    tags:
      - { name: xcart.lifetime-hook, moduleId: Qualiteam-SkinActXPaymentsConnector, type: enable, method: onEnableOrInstall }
      - { name: xcart.lifetime-hook, moduleId: Qualiteam-SkinActXPaymentsConnector, type: install, method: onEnableOrInstall }
