# vim: set ts=2 sw=2 sts=2 et:
#
# Metadata
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

version: 5.5.0.0
type: common
authorName: Qualiteam
moduleName: 'SkinAct ShipStation Advanced'
description: 'Allowing import orders into ShipStation, and will enable ShipStation to automatically update shipment status in X-Cart. SS-21024'
minorRequiredCoreVersion: 0
dependsOn:
    - ShipStation-Api
    - XC-ProductVariants
incompatibleWith: { }
showSettingsForm: false
canDisable: true
