#
# Module services
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

services:
  _defaults:
    autowire: true
    public: true

  shipstation.configuration:
    class: Qualiteam\SkinActShipStationAdvanced\Api\Config\Config
    factory: [ 'Qualiteam\SkinActShipStationAdvanced\Api\Config\ConfigFactory', 'createConfig' ]

  shipstation.auth:
    class: Qualiteam\SkinActShipStationAdvanced\Api\Auth
    arguments:
      - "@shipstation.configuration"

  shipstation.connect:
    class: Qualiteam\SkinActShipStationAdvanced\Api\Connect
    arguments:
      - "@shipstation.auth"

  shipstation.api:
    class: Qualiteam\SkinActShipStationAdvanced\Api\ShipStationApi
    arguments:
      - "@shipstation.connect"

  shipstation.helper:
    public: true
    class: Qualiteam\SkinActShipStationAdvanced\Helpers\ShipstationApiHelper
    arguments:
      - '@shipstation.api'

  shipstation.tabs.advanced:
    class:  Qualiteam\SkinActShipStationAdvanced\Core\Tabs\Advanced

  shipstation.tabs.statuses:
    class:  Qualiteam\SkinActShipStationAdvanced\Core\Tabs\Statuses

  shipstation.tabs:
    class: Qualiteam\SkinActShipStationAdvanced\Core\Tabs\Tabs
    factory: [ 'Qualiteam\SkinActShipStationAdvanced\Core\Tabs\TabsFactory', 'getTabsData' ]

  Qualiteam\SkinActShipStationAdvanced\LifetimeHook\Hook:
    tags:
      - { name: xcart.lifetime-hook, moduleId: Qualiteam-SkinActShipStationAdvanced, type: enable, method: onEnable }
      - { name: xcart.lifetime-hook, moduleId: Qualiteam-SkinActShipStationAdvanced, type: disable, method: onDisable }

  Qualiteam\SkinActShipStationAdvanced\Core\Task\CheckProductToSyncShipStation:
    tags:
      - { name: kernel.event_listener, event: xcart.cronjob, method: handleTask }

  Qualiteam\SkinActShipStationAdvanced\Core\Task\CheckProductVariantToSyncShipStation:
    tags:
      - { name: kernel.event_listener, event: xcart.cronjob, method: handleTask }