#
# Module services
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

x_cart:
  clean_urls:
    formats:
      # Brand Clean URL’s format
      # possible values:
      # domain/goalbrand
      # domain/goalbrand.html
      #
      # Changing this setting will not affect existing url's
      # and requires to re-deploy your store
      brand: 'domain/goalbrand'

services:
  _defaults:
    autowire: true

  QSL\ShopByBrand\LifetimeHook\Hook:
    tags:
      - { name: xcart.lifetime-hook, moduleId: QSL-ShopByBrand, type: rebuild, method: onRebuild }
      - { name: xcart.lifetime-hook, moduleId: QSL-ShopByBrand, type: upgrade, method: onUpgradeTo5500, version: '5.5.0.0' }
      - { name: xcart.lifetime-hook, moduleId: QSL-ShopByBrand, type: upgrade, method: onUpgradeTo5506, version: '5.5.0.6' }
