# vim: set ts=2 sw=2 sts=2 et:
#
# Metadata
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

version: 5.5.0.5
type: common
authorName: 'X-Cart team'
moduleName: 'Product reviews'
description: 'Adds an ability to add products reviews and manage them in admin area'
minorRequiredCoreVersion: 0
dependsOn: {  }
incompatibleWith: {  }
showSettingsForm: true
canDisable: true
