monolog:
    handlers:
        xlite:
            type: service
            id: monolog.handler.xcfile
            channels: ["!event", "!doctrine"]
        cloudwatch:
            type: service
            id: XCart\Monolog\Handler\CloudWatch
            channels: ["!event", "!doctrine"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
