services:
    _defaults:
        autowire: true
        autoconfigure: true

    XLite\API\Endpoint\CategoryIcon\Transformer\InputTransformerInterface: '@XLite\API\Endpoint\CategoryIcon\Transformer\InputTransformer'
    XLite\API\Endpoint\CategoryIcon\Transformer\InputTransformer: ~
    XLite\API\Endpoint\CategoryIcon\Transformer\OutputTransformerInterface: '@XLite\API\Endpoint\CategoryIcon\Transformer\OutputTransformer'
    XLite\API\Endpoint\CategoryIcon\Transformer\OutputTransformer: ~

    XLite\Controller\API\CategoryIcon\DeleteCategoryIcon:
        tags: [ 'controller.service_arguments' ]

    XLite\API\Endpoint\CategoryIcon\SubIdentifierExtractor\SubIdentifierExtractor:
        tags: [ !php/const XCart\Framework\ApiPlatform\Core\Api\SubIdentifierExtractor\SubIdentifierExtractorInterface::SUB_IDENTIFIER_EXTRACTOR_TAG ]

    XLite\API\Endpoint\CategoryIcon\SubExtension\SubExtension:
        tags: [ !php/const XLite\API\Extension\ItemSubExtension\ItemSubExtensionInterface::ITEM_SUB_EXTENSION_TAG ]

    XLite\API\Endpoint\CategoryIcon\SubIriConverter\SubIriConverter:
        tags: [ !php/const XCart\Framework\ApiPlatform\Core\Bridge\Symfony\Routing\SubIriConverter\SubIriFromItemConverterInterface::SUB_IRI_FROM_ITEM_CONVERTER_TAG ]
