#
# Module services
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

services:
  QSL\SpecialOffersBase\Core\EventListener:
    tags:
      - { name: kernel.event_listener, event: xcart.service.view-list.collect-mutation.after, method: onCollectViewListMutationsAfter }

  QSL\SpecialOffersBase\LifetimeHook\Hook:
    tags:
      - { name: xcart.lifetime-hook, moduleId: QSL-SpecialOffersBase, type: rebuild, method: onRebuild }
      - { name: xcart.lifetime-hook, moduleId: QSL-SpecialOffersBase, type: upgrade, method: onUpgradeTo5500, version: '5.5.0.0' }
