# vim: set ts=2 sw=2 sts=2 et:
#
# Fixtures
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

XLite\Model\LanguageLabel:
  - { name: "SkinActVideoFeatureWidget educational videos", translations: [{ code: en, label: "Educational videos" }] }
  - { name: "SkinActVideoFeatureWidget see all", translations: [{ code: en, label: "SEE ALL" }] }

XLite\Model\Config:
  - name: educational_videos_limit
    category: Qualiteam\SkinActVideoFeatureWidget
    type: XLite\View\FormField\Input\Text
    orderby: 10
    value: 3
    translations:
      - code: en
        option_name: Number of videos on the homepage widget