# vim: set ts=2 sw=2 sts=2 et:
#
# Metadata
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

version: 5.5.0.6
type: common
authorName: 'X-Cart team'
moduleName: 'Free Shipping and Shipping freights'
description: 'Attract more customers by offering Free Shipping. Mark the products that are shipped for free. Add a possibility to specify shipping freight to products.'
minorRequiredCoreVersion: 0
dependsOn: {  }
incompatibleWith: {  }
showSettingsForm: true
canDisable: true
