version: 5.5.0.4
type: payment
authorName: "Ilya I"
moduleName: "CloverPayments"
description: "This module enables the processing of one-time payments."
minorRequiredCoreVersion: 0
dependsOn: {}
incompatibleWith: {}
showSettingsForm: true
canDisable: true
