# vim: set ts=2 sw=2 sts=2 et:
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

XLite\Model\Config:
  - name: linkedProductMaxQty
    category: 'Qualiteam\SkinActLinkProductsToAttributes'
    type: \XLite\View\FormField\Input\Text\Integer
    orderby: 10
    value: 0
    translations:
      - code: en
        option_name: 'SkinActLinkProductsToAttributes Linked product max qty (main product qty * N)'

XLite\Model\LanguageLabel:
  - { name: "SkinActLinkProductsToAttributes Linked product max qty (main product qty * N)", translations: [{ code: en, label: "Linked product max qty (main product qty * N)" }] }
