# vim: set ts=2 sw=2 sts=2 et:
#
# Metadata
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

version: 5.5.0.4
type: common
authorName: Qualiteam
moduleName: 'Google reCAPTCHA'
description: 'Integrates with Google reCAPTCHA service that protects your site from spam and abuse. It uses advanced risk analysis techniques to tell humans and bots apart.'
minorRequiredCoreVersion: 0
dependsOn: {  }
incompatibleWith: {  }
showSettingsForm: true
canDisable: true
