# vim: set ts=2 sw=2 sts=2 et:
#
# Metadata
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

version: 5.5.0.12
type: payment
authorName: 'X-Cart team'
moduleName: PayPal
description: 'Enables taking payments for your online store via PayPal services.'
minorRequiredCoreVersion: 0
dependsOn: {  }
incompatibleWith:
    - CDev-PaypalWPS
showSettingsForm: true
canDisable: true
autoloader:
    - vendor/autoload.php
