# vim: set ts=2 sw=2 sts=2 et:
#
# Fixtures
#
# Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
# See https://www.x-cart.com/license-agreement.html for license details.

XLite\Model\Config:
  - name: invoice_payment_method_id
    category: Qualiteam\SkinActInvoiceToQuote
    type: Qualiteam\SkinActInvoiceToQuote\View\FormField\Select\OrderPaymentStatuses
    orderby: 10
    translations:
      - code: en
        option_name: SkinActInvoiceToQuote order payment status

XLite\Model\LanguageLabel:
  - { name: "SkinActInvoiceToQuote order payment status", translations: [{ code: en, label: "Order payment status:" }] }
  - { name: "SkinActInvoiceToQuote order payment status not selected", translations: [{ code: en, label: "Order payment status not selected" }] }
  - { name: "SkinActInvoiceToQuote print quote", translations: [{ code: en, label: "Print quote" }] }
  - { name: "SkinActInvoiceToQuote quote", translations: [{ code: en, label: "Quote" }] }
  - { name: "SkinActInvoiceToQuote quote #{{orderId}}, {{time}}", translations: [{ code: en, label: "Quote #{{orderId}}, {{time}}" }] }
  - { name: "SkinActInvoiceToQuote quote X", translations: [{ code: en, label: "Quote #{{id}}" }] }
  - { name: "SkinActInvoiceToQuote order quote", translations: [{ code: en, label: "Order quote" }] }
  - { name: "SkinActInvoiceToQuote order number quote", translations: [{ code: en, label: "Order {{number}} quote" }] }
  - { name: "SkinActInvoiceToQuote open pdf quote", translations: [{ code: en, label: "Open PDF quote" }] }
