<?php
/**
 * Copyright (c) 2011-present Qualiteam software Ltd. All rights reserved.
 * See https://www.x-cart.com/license-agreement.html for license details.
 */

namespace Qualiteam\SkinActKlarna\View\FormField\Select;

use XLite\Model\WidgetParam\TypeCollection;
use XLite\View\FormField\Select\Regular;

class KlarnaCategories extends Regular
{
    public const PARAM_KLARNA_METHODS = 'klarnaMethods';

    protected function getMethods()
    {
        return $this->getParam(self::PARAM_KLARNA_METHODS);
    }

    protected function defineWidgetParams()
    {
        parent::defineWidgetParams();

        $this->widgetParams += [
            self::PARAM_KLARNA_METHODS => new TypeCollection(
                'Klarna methods',
                []
            ),
        ];
    }

    protected function getDefaultWrapperClass()
    {
        return parent::getDefaultWrapperClass() . ' hidden'; // TODO: Change the autogenerated stub
    }

    protected function getOptions()
    {
        $result = [];

        foreach ($this->getMethods() as $method) {
            $result[$method['identifier']] = $method['name'];
        }

        return $result;
    }
}